// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClfABxw4ZDv-yx-AcjFfUy5-9XQ99G7nA',
    appId: '1:714707690632:web:abcdef123456',
    messagingSenderId: '714707690632',
    projectId: 'shift-management-navigator',
    authDomain: 'shift-management-navigator.firebaseapp.com',
    storageBucket: 'shift-management-navigator.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfABxw4ZDv-yx-AcjFfUy5-9XQ99G7nA',
    appId: '1:714707690632:android:15fa2f9543e25a5d572b3d',
    messagingSenderId: '714707690632',
    projectId: 'shift-management-navigator',
    storageBucket: 'shift-management-navigator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClfABxw4ZDv-yx-AcjFfUy5-9XQ99G7nA',
    appId: '1:714707690632:ios:abcdef123456',
    messagingSenderId: '714707690632',
    projectId: 'shift-management-navigator',
    iosBundleId: 'com.shiftmanagement.shiftManagementNavigator',
    storageBucket: 'shift-management-navigator.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClfABxw4ZDv-yx-AcjFfUy5-9XQ99G7nA',
    appId: '1:714707690632:macos:abcdef123456',
    messagingSenderId: '714707690632',
    projectId: 'shift-management-navigator',
    iosBundleId: 'com.shiftmanagement.shiftManagementNavigator',
    storageBucket: 'shift-management-navigator.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClfABxw4ZDv-yx-AcjFfUy5-9XQ99G7nA',
    appId: '1:714707690632:windows:abcdef123456',
    messagingSenderId: '714707690632',
    projectId: 'shift-management-navigator',
    authDomain: 'shift-management-navigator.firebaseapp.com',
    storageBucket: 'shift-management-navigator.firebasestorage.app',
  );
}
